### ISSUE TITLE
Stop requireing Devel::Cover

### ISSUE THREAD

**Issue by szabgab** [manwar/Test-Strict#17]
I think most of the people who use Test::Critic don't need the functionality provided by Devel::Cover. IMHO Test::Strict should not depend on it and if the user invokes the `all_cover_ok` then it should be checked if Devel::Cover is installed.

**Comment by ribasushi** [comment]
+1

>  if the user invokes the all_cover_ok then it should be checked if Devel::Cover is installed

This is [already the case](https://metacpan.org/source/MANWAR/Test-Strict-0.36/lib/Test/Strict.pm#L455). The only part missing is [this](https://metacpan.org/source/MANWAR/Test-Strict-0.36/Makefile.PL#L17) being changed to "recommends" or somesuch.

Currently Devel::Cover [does not build on blead](https://github.com/pjcj/Devel--Cover/issues/161), and as such drags this module with it.

**Comment by ribasushi** [comment]
@manwar @szabgab ping: this is still a problem!

**Comment by manwar** [comment]
Hi @ribasushi, 

I will sort this out be end of play today.

Best Regards,
Mohammad S Anwar

**Comment by ribasushi** [comment]
The [current solution](https://metacpan.org/diff/file?target=MANWAR/Test-Strict-0.42/&source=MANWAR%2FTest-Strict-0.41) is suboptimal. While it does solve my problem of reducing the dependency footrpint, it would not alert an end-user who requested `all_cover_ok` that D::C is not even available. Instead it emits a `diag()` ( which nobody is even able to see courtesy of how `cpanm` operates ) and `SKIP_ALL`s out of the test.

You should consider failing the test when `D::C` is not available, and documenting that it must now be specified explicitly as a dependency.

**Comment by ribasushi** [comment]
This seems to have been resolved, @szabgab I'd close

**Comment by jkeenan** [comment]
> This seems to have been resolved, @szabgab I'd close

@manwar, ^^

**Comment by manwar** [comment]
Closing the issue as confirmed above.
