### ISSUE TITLE
all_perl_files_ok should skip .git

### ISSUE THREAD

**Issue by rra** [manwar/Test-Strict#26]
`Test::Strict::all_perl_files_ok` contains hard-coded logic to exclude `CVS` and `.svn` directories, but doesn't skip `.git` directories.  It does provide a way to pass in a list of files to skip, but that is applied as a filter to the list of individual files, so it cannot be used to skip directories.

This means that if there are Perl files in `.git` (which may be the case if one has used dgit from this checkout, since it makes its own private copy of the unpacked source package), they will be picked up and tested incorrectly by this module.

The quick fix is that `.git` should be added to the hard-coded skip list in the module.  A better, complementary fix would be to move processing of `$Test::Skip::TEST_SKIP` into `$want_sub` in `_all_files` and use it to prune directories as well.  I think it's safe to assume this is what the caller would want if they list a directory in `TEST_SKIP`.

**Comment by manwar** [comment]
Resolved in Test:;Strict v0.51
