### ISSUE TITLE
01all.t failures with 0.53

### ISSUE THREAD

**Issue by sdt** [manwar/Test-Strict#36]
Hello, I've been getting the following failure with t/01all.t in 0.53

```
cpanm (App::cpanminus) 1.7047 on perl 5.034000 built for x86_64-linux-gnu-thread-multi
...
t/00-load.t ............ 1/1 # Testing Test::Strict 0.53, Perl 5.034000, /usr/bin/perl
t/00-load.t ............ ok
t/01all.t .............. # First all_perl_files_ok starting
t/01all.t .............. 15/59 # First all_perl_files_ok done
# Start creating files in /tmp/vB_U41e3nO
# [
#   '/tmp/Ry7Y2QJ9DC/ekr57wqvKv.pl',
#   '/tmp/Ry7Y2QJ9DC/EGxPYyxZTM.pl',
#   '/tmp/Ry7Y2QJ9DC/MSCToOfTQg.pl',
#   '/tmp/Ry7Y2QJ9DC/pCTAd0A_xJ.pl'
# ]
# File to skip: /tmp/Ry7Y2QJ9DC/EGxPYyxZTM.pl
# Start all_perl_files_ok on /tmp/Ry7Y2QJ9DC (should be 2*3 = 6 tests)
# Looks like you planned 59 tests but ran 57.
t/01all.t .............. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/59 subtests
```

Getting the same failure with these setups:

* cpanm (App::cpanminus) 1.7047 on perl 5.034000 built for x86_64-linux-gnu-thread-multi
* cpanm (App::cpanminus) 1.7047 on perl 5.038002 built for x86_64-linux
* Running cpm 0.997015 on perl 5.34.0 built for x86_64-linux-gnu-thread-multi (/usr/bin/perl)
* Running cpm 0.997015 on perl 5.34.1 built for darwin-thread-multi-2level (/usr/bin/perl)

**Comment by eserte** [comment]
The test suite fails everywhere: http://fast-matrix.cpantesters.org/?dist=Test-Strict%200.53 (currently 178 fail reports, no pass report).

**Comment by esabol** [comment]
Is this fixed in version 0.54?

**Comment by jkeenan** [comment]
> Is this fixed in version 0.54?

AFAICT, this has been fixed.  Please try 0.54.

**Comment by sdt** [comment]
0.54 is working for me. Thanks @manwar !

**Comment by manwar** [comment]
Closing the issue as confirmed above.
